["PARAMETER"]
additionalModels="SO_Nutzungsplanung_20171118_Validierung_20190129;SO_FunctionsExt"

["SO_Nutzungsplanung_20171118.Rechtsvorschriften.Dokument.TextImWeb"]
type="warning"

["SO_Nutzungsplanung_20171118_Validierung_20190129.Nutzungsplanung_Validierung.v_Grundnutzung.checkMinimumFlaeche"]
check="warning"

["SO_Nutzungsplanung_20171118_Validierung_20190129.Nutzungsplanung_Validierung.v_Ueberlagernd_Flaeche.checkMinimumFlaeche"]
check="warning"

["SO_Nutzungsplanung_20171118_Validierung_20190129.Nutzungsplanung_Validierung.v_Erschliessung_Flaechenobjekt.checkMinimumFlaeche"]
check="warning"