name: CI/CD

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate build number
        uses: einaregilsson/build-number@v2 
        with:
          token: ${{secrets.GITHUB_TOKEN}}        
      - name: Print new build number
        run: echo "Build number is $BUILD_NUMBER"
      - uses: actions/checkout@v1
      - uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Gradle
        run: ./gradlew clean build 
      - name: Build docker image
        run: |
          export CI_JOB_TIMESTAMP=$(date +%Y%m%dT%H%M%S)
          echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
          docker pull $DOCKER_ACCOUNT/$DOCKER_REPO:latest || true        
          docker build --pull --label $DOCKER_REPO.git_commit=$GITHUB_SHA --label $DOCKER_REPO.build=1.0.$BUILD_NUMBER --label $DOCKER_REPO.created=$CI_JOB_TIMESTAMP --cache-from $DOCKER_ACCOUNT/$DOCKER_REPO:latest -t $DOCKER_ACCOUNT/$DOCKER_REPO:latest -t $DOCKER_ACCOUNT/$DOCKER_REPO:1.0.$BUILD_NUMBER .
          docker images
          docker push $DOCKER_ACCOUNT/$DOCKER_REPO:latest 
          docker push $DOCKER_ACCOUNT/$DOCKER_REPO:1.0.$BUILD_NUMBER
        env:
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
          DOCKER_ACCOUNT: sogis
          DOCKER_REPO: ilivalidator-web-service
      