name: CI/CD

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Gradle
        run: ./gradlew clean build -x test
      - name: Export timestamp
        run: export CI_JOB_TIMESTAMP=$(date +%Y%m%dT%H%M%S)
      - name: Build docker image
        run: docker build -t sogis/ilivalidator-web-service-websocket .
        run: |
          docker pull sogis/ilivalidator-web-service-websocket:latest || true        
          docker build --pull --label ilivalidator-web-service-websocket.git_commit=$GITHUB_SHA --label ilivalidator-web-service-websocket.created=$CI_JOB_TIMESTAMP --cache-from sogis/ilivalidator-web-service-websocket:latest -t sogis/ilivalidator-web-service-websocket .
          docker images
          echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
          docker push sogis/ilivalidator-web-service-websocket:latest 
